name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node
        run: |
          npm install -g react-native-cli
          npm install -g detox-cli
          npm install -g yarn
      - name: Install Detox
        run: |
          cd space
          brew tap wix/brew
          brew install applesimutils
      - name: Install Yarn Dependencies
        run: yarn install
      - name: Install Pod Dependencies
        run: cd ./ios && pod install && cd ..
      - name: Detox Build
        run: detox build --configuration ios.sim.release
      - name: Detox Test
        run: detox test --configuration ios.sim.release --cleanup
